// <auto-generated />
using System;
using LetusCountApplication.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LetusCountApplication.Infrastructure.Migrations
{
    [DbContext(typeof(LetusCountApplicationContext))]
    partial class LetusCountApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LetusCountApplication.Domain.Models.EFModels.Cash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Cashes", "dep");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.EFModels.CashCashMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CashId")
                        .HasColumnType("integer");

                    b.Property<int>("CashMachineId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndWorking")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartWorking")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CashId");

                    b.HasIndex("CashMachineId");

                    b.ToTable("CashCashMachines", "dep");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.EFModels.CashMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("CashMachines", "dep");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.EFModels.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Departments", "dep");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.EFModels.Cash", b =>
                {
                    b.HasOne("LetusCountApplication.Domain.Models.EFModels.Department", "Department")
                        .WithMany("Cashes")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.EFModels.CashCashMachine", b =>
                {
                    b.HasOne("LetusCountApplication.Domain.Models.EFModels.Cash", "Cash")
                        .WithMany("CashCashMachines")
                        .HasForeignKey("CashId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LetusCountApplication.Domain.Models.EFModels.CashMachine", "CashMachine")
                        .WithMany("CashCashMachine")
                        .HasForeignKey("CashMachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cash");

                    b.Navigation("CashMachine");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.EFModels.Cash", b =>
                {
                    b.Navigation("CashCashMachines");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.EFModels.CashMachine", b =>
                {
                    b.Navigation("CashCashMachine");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.EFModels.Department", b =>
                {
                    b.Navigation("Cashes");
                });
#pragma warning restore 612, 618
        }
    }
}
