// <auto-generated />
using System;
using LetusCountApplication.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LetusCountApplication.Infrastructure.Migrations
{
    [DbContext(typeof(LetusCountApplicationContext))]
    partial class LetusCountApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LetusCountApplication.Domain.Models.Banknote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DenomName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("OperationUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Value")
                        .HasMaxLength(32)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperationUnitId");

                    b.ToTable("Banknotes", "opr", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.Cash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("WorkStatus")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Cashes", "dep");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.CashCashMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CashId")
                        .HasColumnType("integer");

                    b.Property<int>("CashMachineId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndWorking")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartWorking")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CashId");

                    b.HasIndex("CashMachineId");

                    b.ToTable("CashCashMachines", "dep");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.CashMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("CashMachines", "dep");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("WorkStatus")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Departments", "dep");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineSerial")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Operations", "opr", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.OperationUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("OperationUnits", "opr", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.Banknote", b =>
                {
                    b.HasOne("LetusCountApplication.Domain.Models.OperationUnit", "OperationUnit")
                        .WithMany("Banknotes")
                        .HasForeignKey("OperationUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OperationUnit");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.Cash", b =>
                {
                    b.HasOne("LetusCountApplication.Domain.Models.Department", "Department")
                        .WithMany("Cashes")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.CashCashMachine", b =>
                {
                    b.HasOne("LetusCountApplication.Domain.Models.Cash", "Cash")
                        .WithMany("CashCashMachines")
                        .HasForeignKey("CashId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LetusCountApplication.Domain.Models.CashMachine", "CashMachine")
                        .WithMany("CashCashMachine")
                        .HasForeignKey("CashMachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cash");

                    b.Navigation("CashMachine");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.OperationUnit", b =>
                {
                    b.HasOne("LetusCountApplication.Domain.Models.Operation", "Operation")
                        .WithMany("OperationUnits")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.Cash", b =>
                {
                    b.Navigation("CashCashMachines");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.CashMachine", b =>
                {
                    b.Navigation("CashCashMachine");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.Department", b =>
                {
                    b.Navigation("Cashes");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.Operation", b =>
                {
                    b.Navigation("OperationUnits");
                });

            modelBuilder.Entity("LetusCountApplication.Domain.Models.OperationUnit", b =>
                {
                    b.Navigation("Banknotes");
                });
#pragma warning restore 612, 618
        }
    }
}
