// <auto-generated />
using System;
using LetusCountService.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LetusCountService.Infrastructure.Migrations
{
    [DbContext(typeof(LetusCountServiceContext))]
    partial class LetusCountServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LetusCountService.Domain.Models.Banknote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DenomName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("OperationUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Value")
                        .HasMaxLength(32)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperationUnitId");

                    b.ToTable("Banknotes", "opr");
                });

            modelBuilder.Entity("LetusCountService.Domain.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineSerial")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Operations", "opr");
                });

            modelBuilder.Entity("LetusCountService.Domain.Models.OperationUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("OperationUnits", "opr");
                });

            modelBuilder.Entity("LetusCountService.Domain.Models.Banknote", b =>
                {
                    b.HasOne("LetusCountService.Domain.Models.OperationUnit", "OperationUnit")
                        .WithMany("Banknotes")
                        .HasForeignKey("OperationUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OperationUnit");
                });

            modelBuilder.Entity("LetusCountService.Domain.Models.OperationUnit", b =>
                {
                    b.HasOne("LetusCountService.Domain.Models.Operation", "Operation")
                        .WithMany("OperationUnits")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("LetusCountService.Domain.Models.Operation", b =>
                {
                    b.Navigation("OperationUnits");
                });

            modelBuilder.Entity("LetusCountService.Domain.Models.OperationUnit", b =>
                {
                    b.Navigation("Banknotes");
                });
#pragma warning restore 612, 618
        }
    }
}
